# Generated by Django 5.2.12 on 2026-04-11 01:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('empresa', 'Empresa'), ('secretaria', 'Secretaria'), ('prefeitura', 'Prefeitura')], default='empresa', max_length=30)),
                ('responsavel', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cidade', models.CharField(blank=True, max_length=120)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('periodo_melhoria_inicio', models.DateField(blank=True, null=True)),
                ('periodo_melhoria_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('iniciar', 'A iniciar'), ('execucao', 'Em execução'), ('concluido', 'Concluído'), ('pausado', 'Pausado')], default='iniciar', max_length=20)),
                ('causa_gargalo', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='monitoramento.cliente')),
            ],
            options={
                'ordering': ['-periodo_inicio', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='monitoramento.cliente')),
                ('lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_lideradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('cliente', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('funcao', models.CharField(blank=True, max_length=120)),
                ('dias_trabalho', models.CharField(blank=True, max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='monitoramento.cliente')),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='monitoramento.equipe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(blank=True, max_length=30)),
                ('nome', models.CharField(max_length=160)),
                ('descricao', models.TextField(blank=True)),
                ('unidade', models.CharField(default='un', max_length=30)),
                ('meta_valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_atual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ativo', models.BooleanField(default=True)),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='monitoramento.diagnostico')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AcaoMelhoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=180)),
                ('descricao', models.TextField(blank=True)),
                ('meta_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa'), ('concluida', 'Concluída')], default='ativa', max_length=20)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_responsavel', to=settings.AUTH_USER_MODEL)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='monitoramento.indicador')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('admin', 'Admin da Consultoria'), ('cliente', 'Gestor do Cliente'), ('funcionario', 'Funcionário')], default='funcionario', max_length=20)),
                ('cargo', models.CharField(blank=True, max_length=120)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfis', to='monitoramento.cliente')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=180)),
                ('descricao', models.TextField(blank=True)),
                ('meta_quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10)),
                ('concluida', models.BooleanField(default=False)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='monitoramento.acaomelhoria')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='monitoramento.funcionario')),
            ],
            options={
                'ordering': ['prazo', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('descricao_atividade', models.TextField()),
                ('quantidade_realizada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('justificativa', models.TextField(blank=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='monitoramento.funcionario')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='monitoramento.tarefa')),
            ],
            options={
                'ordering': ['-data', '-created_at'],
            },
        ),
    ]
