# Generated by Django 6.0.4 on 2026-04-11 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='quantidade_prevista',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='situacao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('atrasada', 'Atrasada'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluida')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='previsto_quantidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='situacao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('atrasada', 'Atrasada'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluida')], default='pendente', max_length=20),
        ),
        migrations.CreateModel(
            name='AcaoAtribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valor_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ativo', models.BooleanField(default=True)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes', to='monitoramento.acaomelhoria')),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes_acao', to='monitoramento.equipe')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes_acao', to='monitoramento.funcionario')),
            ],
            options={
                'ordering': ['-ativo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IndicadorHistoricoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competencia', models.DateField(help_text='Use o primeiro dia do mes como referencia.')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('meta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='monitoramento.indicador')),
            ],
            options={
                'ordering': ['-competencia'],
                'unique_together': {('indicador', 'competencia')},
            },
        ),
    ]
