# Generated by Django 6.0.4 on 2026-04-11 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0002_funcionario_email_funcionario_telefone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo_acesso',
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_funcionario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UsuarioCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('admin', 'Admin da Consultoria'), ('cliente', 'Gestor do Cliente'), ('funcionario', 'Funcionário')], default='funcionario', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_acesso', to='monitoramento.cliente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_acesso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['cliente__nome', 'user__username'],
                'unique_together': {('user', 'cliente')},
            },
        ),
    ]
