# Generated by Codex on 2026-04-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoramento", "0003_cliente_codigo_acesso_alter_funcionario_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="acaoatribuicao",
            name="modo_rateio",
            field=models.CharField(
                choices=[("automatico", "Automatico"), ("manual", "Manual")],
                default="automatico",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AcaoAtribuicaoDistribuicao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("valor_mensal", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("atribuicao", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="distribuicoes", to="monitoramento.acaoatribuicao")),
                ("funcionario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="distribuicoes_acao", to="monitoramento.funcionario")),
            ],
            options={
                "ordering": ["funcionario__user__first_name", "funcionario__user__username"],
                "unique_together": {("atribuicao", "funcionario")},
            },
        ),
    ]
