# Generated by Django 6.0.4 on 2026-04-13 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0005_indicadormetavigencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='JustificativaNaoAtingimentoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competencia', models.DateField(help_text='Use o primeiro dia do mes como referencia.')),
                ('justificativa', models.TextField()),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificativas_mensais', to='monitoramento.funcionario')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificativas_mensais', to='monitoramento.tarefa')),
            ],
            options={
                'ordering': ['-competencia', '-updated_at'],
                'unique_together': {('tarefa', 'competencia')},
            },
        ),
    ]
